// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/status.get').default>>>>
    }
    '/api/github/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/github/[...]').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.post').default>>>>
    }
    '/api/projects/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].get').default>>>>
    }
    '/api/projects/:id/comment-counts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/comment-counts.get').default>>>>
    }
    '/api/projects/:id/comments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/comments.get').default>>>>
    }
    '/api/projects/:id/comments/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/comments/sync.post').default>>>>
    }
    '/api/projects/:id/file': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/file.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/file.get').default>>>>
    }
    '/api/projects/:id/tree': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/tree.get').default>>>>
    }
    '/api/repos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/repos.get').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}